### ISSUE TITLE
DBD::ODBC no longer on CPAN

### ISSUE THREAD

**Issue by genio** [perl5-dbi/DBD-ODBC#7]
1.57 was released, but then removed. So, there isn't a current indexed version out there on CPAN. Can you re-upload 1.57 or increment and release a 1.58 please?

Thanks,
Chase

**Comment by genio** [comment]
https://rt.cpan.org/Public/Bug/Display.html?id=124821

**Comment by genio** [comment]
However, the changes allowing for the environment variable flag for unicode support in 1.57 were reverted. If we could get a 1.58 out soon, that'd be greatly appreciated.

**Comment by mjegh** [comment]
I had other changes outstanding and unfortunately discovered a major problem after I uploaded it which was tricky to resolve and so I removed it. I forgot to reindex. I'll put a new version up today. Sorry for the inconvenience.

**Comment by mjegh** [comment]
1.58 is on its way to the CPAN.
